[package]
name = "cicd-tp"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["tokio"] }
sqlx = "0.8.3"
tokio = { version = "1.44.0", features = ["rt-multi-thread"] }
