services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: cicd
      POSTGRES_PASSWORD: cicd
      POSTGRES_DB: cicd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d/

volumes:
  db_data:
