services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: cicd
      POSTGRES_PASSWORD: cicd
      POSTGRES_DB: cicd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres_init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

  grafana:
    image: grafana/grafana:11.6.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./services/grafana/:/etc/grafana/
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.53.4
    ports:
      - "9090:9090"
    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    extra_hosts:
      - "cicd-tp:host-gateway"

volumes:
  db_data:
  prom_data:
