apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db-{{include "cicdtp.db_name" . }}
spec:
  name: {{include "cicdtp.db_name" . }}
  owner: app
  cluster:
    name: {{ .Values.pg_cluster.name }}
