apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .Release.Name }}
spec:
  databaseReclaimPolicy: delete
  name: {{include "cicdtp.db_name" . }}
  owner: app
  cluster:
    name: {{ .Values.pg_cluster.name }}
