apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
    {{- if .Values.dev.is }}
    - host: "pr-{{ .Values.dev.pr_number }}-{{ .Values.ingress.domain }}"
    {{- else }}
    - host: {{ .Values.ingress.domain }}
    {{- end }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 8080
