name: Check source code

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/check.yml'
      - '.gitignore'

jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2.7.8

      - name: Run cargo check
        run: cargo check --all-features

      - name: Run Clippy
        run: cargo clippy --all-features -- -D warnings
    
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Run cargo fmt
        run: cargo fmt -- --check
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal
      
      - name: Setup postgres database
        run: docker compose up --wait -d

      - uses: Swatinem/rust-cache@v2.7.8

      - name: Run cargo test
        env:
          DATABASE_URL: postgres://cicd:cicd@localhost:5432/cicd
        run: cargo test --all-features
